/**
 * Writes the privacy policy and the terms as real pages: public/privacy.html
 * and public/terms.html, served at offside.win/privacy and offside.win/terms.
 *
 * Why they exist at all: the app shows these at #/legal/<page>, which only
 * exists once the app's script has run. Google's brand verification (the
 * check that lets the sign-in window show "offside.win" and the logo) reads
 * the privacy policy at its URL, and a crawler that reads the raw page would
 * find the front page there instead. So the same text, from the same module,
 * is also written out as plain HTML.
 *
 *   node scripts/legal-pages.mjs          write the files
 *   node scripts/legal-pages.mjs --check  exit 1 if they are out of date
 *
 * engine/test/legal-pages.test.ts runs the check, so an edit to the legal
 * text that forgets to regenerate these fails CI instead of shipping two
 * versions of a privacy policy.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const PAGES = { privacy: 'privacy.html', terms: 'terms.html' };

export async function render(which) {
  const { LEGAL, UPDATED } = await import(pathToFileURL(join(ROOT, 'public/js/lib/legal.js')).href);
  const page = LEGAL[which];
  // Links into the app become links to the app from here.
  const body = page.body.replace(/href="#\//g, 'href="/#/');
  return `<!doctype html>
<html lang="en-GB">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${page.title}: offside.win</title>
<meta name="description" content="${page.title} for offside.win, which publishes football match analysis and a call on the biggest games.">
<link rel="canonical" href="https://offside.win/${which}">
<link rel="icon" href="/icon.svg" type="image/svg+xml">
<link rel="stylesheet" href="/tokens.css">
<link rel="stylesheet" href="/base.css">
<link rel="stylesheet" href="/components.css">
</head>
<body>
<!-- Generated by scripts/legal-pages.mjs from public/js/lib/legal.js. Edit that, not this. -->
<header class="top"><div class="wrap top-inner">
  <a class="brand" href="/" aria-label="offside.win, home"><span class="wordmark" aria-hidden="true">off<i class="wm-line"></i>side<span class="wm-tld">.win</span></span></a>
</div></header>
<main><div class="wrap section">
  <div class="section-head"><div><h1 class="display">${page.title}</h1>
    <p>Last updated ${UPDATED}.</p></div></div>
  <div class="prose">${body}</div>
  <p class="prose"><a href="/">Back to offside.win</a></p>
</div></main>
</body>
</html>
`;
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  const check = process.argv.includes('--check');
  let stale = 0;
  for (const [which, file] of Object.entries(PAGES)) {
    const path = join(ROOT, 'public', file);
    const html = await render(which);
    if (check) {
      let now = '';
      try { now = readFileSync(path, 'utf8'); } catch { /* missing counts as stale */ }
      if (now !== html) { stale++; console.error(`public/${file} is out of date: run node scripts/legal-pages.mjs`); }
    } else {
      writeFileSync(path, html);
      console.log(`wrote public/${file}`);
    }
  }
  if (stale) process.exit(1);
}
